### ISSUE TITLE
Build Example for Fragments

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#102]
### Phase 1 - Content only

- [x] Create an example where a part of a page is loaded from a fragment
- [x] Re-use https://www.hlx.live/developer/block-collection/fragment if possible
- [ ] Please present the result in the next meeting with Hanes

### Phase 2 - Product Enrichment

- [ ] Add product or category metadata to fragments
- [ ] Add an index for fragments including their metadata
- [ ] Create a new block (similar to `fragment`) which can read the product/category identifiers from the URL, looks up matching fragments from the index and displays them
- [ ] Create an example and present the result
