### ISSUE TITLE
Product Recommendations

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#18]
- [x] Understand current product recommendation approach
    - Currently not using product recommendations by Adobe Commerce.
- [x] Decide if using 3rd party service or ootb Commerce PRecs service
### Phase 1 ✅ 
- [x] Implement and add recommendation blocks using Sitecore / Reflektion
### Phase 2
- ~~[ ] Use Product Recommendations from Adobe Commerce~~
    - [x] https://experienceleague.adobe.com/docs/commerce-merchant-services/product-recommendations/getting-started/headless.html?lang=en
    - [x] Install `magento/module-data-services-graphql` module as documented in https://developer.adobe.com/commerce/pwa-studio/integrations/product-recommendations/#install-the-product-recommendations-module to expose `dataServicesStorefrontInstanceContext` query via GraphQL.
- [x] Install [Storefront Events SDK](https://github.com/adobe/commerce-events/tree/main/packages/storefront-events-sdk) and ~~[initialize](https://github.com/adobe/commerce-events/tree/main/packages/storefront-events-sdk#setstorefrontinstance) it with the data from `dataServicesStorefrontInstanceContext` query.~~
- [x] Get access to Reflektion product recommendations API, see #76 
- [ ] Build product recommendations API block that displays products from the API
- [ ] Validate setup

**Comment by herzog31** [comment]
Blocked by missing setup of product recommendations / Commerce Catalog Sync.

**Comment by herzog31** [comment]
Blocked by missing product recommendations API from Reflektion.
