### ISSUE TITLE
Go-Live Checklist

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#259]
- [ ] Switch to Catalog Service production endpoint (`franklin.maidenform.com/cs-graphql`)
- [ ] Sync catalog from production environment to catalog service
- [ ] Use production GraphQL endpoint (`maidenform.com/graphql`). Needs to be changed in CDN.
