### ISSUE TITLE
Product Search

### ISSUE THREAD

**Issue by herzog31** [hlxsites/maidenform#76]
### Phase 1
- [x] Setup search popup via Sitecore / Reflektion
- [x] ~~Create Product Search Page block and implement via Sitecore / Reflektion~~
### Phase 2
- [x] ~~Setup LiveSearch according to https://experienceleague.adobe.com/docs/commerce-merchant-services/live-search/onboard/install.html?lang=en~~
- [x] Make Reflektion API available
    - via https://secretshare.corp.adobe.com/?42e5733a1838a77c&k=DPrwyiQyQxF2ffYzpawPXJLYpPuEkVU49TQUN1LX6pkM
- [ ] Implement Product Search Page block, re-use PLP from https://github.com/hlxsites/maidenform/issues/10
- [x] Use Reflektion API to fill block with data

**Comment by herzog31** [comment]
Currently blocked by lack of documentation available for Sitecore / Reflektion.

**Comment by herzog31** [comment]
Currently blocked by missing setup of Live Search

**Comment by herzog31** [comment]
Currently blocked by missing search API for Reflektion.
